# Generated by Django 5.1.1 on 2024-09-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='type',
            field=models.CharField(choices=[('File', 'File'), ('Box File', 'Box File')], max_length=50),
        ),
    ]
