# Generated by Django 5.1.1 on 2024-09-18 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filemanagement', '0007_remove_filemovement_movement_delete_filelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=100, unique=True)),
                ('name_of_file', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('CHOOSE DEPARTMENT', 'Choose Department'), ('ADM', 'Administration'), ('HR', 'Human Resources'), ('PUB', 'Publicity & Communications'), ('PROC', 'Procurement'), ('PRM', 'Property Management'), ('CBN', 'Claims & Benefits'), ('HSP', 'Hospitals'), ('MEM', 'Membership'), ('LEG', 'Legal'), ('TRS', 'Transport'), ('REP', 'Reports'), ('ST', 'Standards'), ('FIN', 'Finance'), ('C', 'Confidential')], default='CHOOSE DEPARTMENT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('basic_holder', models.CharField(default='Central Registry', max_length=50)),
                ('dispatched_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Filemovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_holder', models.CharField(max_length=200)),
                ('location_of_holder', models.CharField(max_length=100)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='filemanagement.filelog')),
            ],
        ),
    ]
