# Generated by Django 5.1.1 on 2024-09-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0009_alter_filelog_created_at_alter_filelog_dispatched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='dispatched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
