# Generated by Django 5.1.1 on 2024-09-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0010_alter_filelog_dispatched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='dispatched_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
