# Generated by Django 5.1.1 on 2024-09-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0012_alter_filelog_created_at_alter_filelog_dispatched_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemovement',
            name='file',
        ),
        migrations.DeleteModel(
            name='Filelog',
        ),
        migrations.DeleteModel(
            name='Filemovement',
        ),
    ]
